export type ProductType = {
    pkid?: number,
    id?: string,
    title: string,
    slug?: string,
    sku: string,
    thumb: string,
    vendor_id: number,
    category_id: number,
    sub_category_id?: number,
    child_category_id?: number,
    brand_id: number,
    quantity: number,
    quantityPerUnit: number,
    short_description: Text,
    long_description: Text,
    videoLink?: Text,
    price: Number,
    offerPrice?: Number,
    offerStartDate?: Date,
    offerEndDate?: Date,
    productType?: string,
    status: Boolean,
    isApproved?: Boolean,
    isAvailable: Boolean,
    unitWeight: Number,
    unitInStock: number,
    unitOnOrder: number, // units in inventory
    reorderLevel: number,
    discountAvailable: Boolean,
    seoTitle: string,
    seoDescription: Text,
    createdBy: string,
}