export type ProductType = {
    pkid?: number,
    id?: string,
    title: string,
    slug?: string,
    sku: string,
    thumb: string,
    vendorId: number,
    categoryId: number,
    subCategoryId?: number,
    childCategoryId?: number,
    brandId: number,
    quantity: number,
    quantityPerUnit: number,
    shortDescription: Text,
    longDescription: Text,
    videoLink?: Text,
    price: Number,
    offerPrice?: Number,
    offerStartDate?: Date,
    offerEndDate?: Date,
    productType?: string,
    status: Boolean,
    isApproved?: Boolean,
    isAvailable: Boolean,
    unitWeight: Number,
    unitInStock: number,
    unitOnOrder: number, // units in inventory
    reorderLevel: number,
    discountAvailable: Boolean,
    seoTitle: string,
    seoDescription: Text,
    createdBy: string,
    createdAt?: Date,
    updatedAt?: Date
}